"""Tale text and painting prompts.

Each episode: series, title, moral, chars (same characters described in every prompt so the four
paintings match), panels = [(caption, scene)]. plate = optional key of an old public-domain plate.
Stories are traditional (Panchatantra, Jataka tales) and retold here in original words.
"""
STYLE = ("Children's storybook illustration, warm painterly cartoon style with clean outlines, rich colours, soft light, "
         "ancient India setting. No text, no letters, no speech bubbles. ")

P = "Panchatantra"
J = "Jataka tales"

EPISODES = [
# ------------------------------------------------------------------ Panchatantra
dict(series=P, title="The Lion and the Clever Hare", moral="Cleverness can do what strength cannot.", plate=None,
     chars="A big golden-maned lion and a small white hare with long ears.",
     panels=[("A greedy lion hunted every animal in the forest, day after day. The animals feared they would all be gone.", "the lion roars on a rock while frightened animals hide in the forest"),
             ("They made a deal. One animal would go to the lion each day, so he would not have to hunt.", "animals gather in a circle and bow before the lion"),
             ("One day it was the little hare's turn. He walked slowly, then told the hungry lion that another lion had stopped him on the way.", "the hare arrives late and tells the angry lion a story, pointing into the forest"),
             ("The hare led him to a deep well. The lion saw his own reflection, roared at the 'rival', and leapt in. The forest was safe again.", "the lion looks down into a stone well at his reflection while the hare watches from the edge")]),
dict(series=P, title="The Monkey and the Crocodile", moral="Keep a calm mind in danger. A quick thought can save you.", plate=None,
     chars="A brown monkey with a friendly face and a large green crocodile.",
     panels=[("A monkey lived in a jamun tree by the river. He shared his sweet fruit with a crocodile, and they became friends.", "the monkey sits in a jamun tree throwing purple fruit to the crocodile on the riverbank"),
             ("The crocodile's wife wanted to eat the monkey's heart. So the crocodile offered the monkey a ride across the river.", "the monkey rides on the crocodile's back in the middle of a wide river"),
             ("In the middle of the river, the crocodile told the truth. The monkey stayed calm. 'My heart is on the tree! Take me back for it.'", "close view of the monkey talking calmly to the surprised crocodile in the river"),
             ("The crocodile swam back. The monkey leapt into the branches and called down, 'A heart never stays outside the body. Go home, foolish friend.'", "the monkey safe in the tree branches waving, the crocodile in the water below looking embarrassed")]),
dict(series=P, title="The Blue Jackal", moral="Borrowed glory does not last. Be yourself.", plate=None,
     chars="A jackal, first golden-brown, then bright blue from dye.",
     panels=[("A hungry jackal wandered into a village and was chased by dogs. He ran, and fell into a huge vat of blue dye.", "a jackal falls into a big vat of blue dye in an Indian village while dogs chase him"),
             ("He climbed out blue from nose to tail. Back in the forest, the animals had never seen such a creature.", "the bright blue jackal stands proudly in the forest as animals stare"),
             ("'I am a king sent by the gods,' he said. Lions, deer and hares bowed. He stopped speaking to the other jackals, who felt ashamed.", "the blue jackal sits on a rock like a king with a lion, deer and hare bowing before him"),
             ("One night a pack of jackals howled far away. Without thinking, the 'king' howled back. The animals knew him at once, and he ran for his life.", "under a full moon the blue jackal howls with his head up, and animals stare in shock")]),
dict(series=P, title="The Crows and the Cobra", moral="Where force fails, a clever plan works.", plate=None,
     chars="A pair of black crows and a green-brown cobra with a raised hood.",
     panels=[("A pair of crows lived in a tree. A cobra in its roots ate their eggs, year after year.", "two sad crows on a tree branch above a cobra coiled near the roots"),
             ("The sad crows flew to a palace garden. One crow picked up a queen's shining necklace in her beak.", "a crow flies off with a sparkling gold necklace from a palace garden pool"),
             ("Guards followed the crow. She dropped the necklace right beside the cobra's hole in the roots.", "the crow drops the necklace near the cobra's hole while palace guards run toward it"),
             ("When the cobra came out, the guards struck it down and took the necklace. The crows lived safely, and hatched their eggs in peace.", "guards take the necklace and the crows sit happily on a nest with new eggs")]),
dict(series=P, title="The Brahmin and the Mongoose", moral="Never act in anger before you know the truth.", plate=None,
     chars="A brown mongoose, a baby in a cradle, and a village couple in simple Indian clothes.",
     panels=[("A family kept a pet mongoose, who loved the baby of the house like a brother.", "a mongoose sits beside a baby sleeping in a cradle in an Indian home"),
             ("One day the mother went to fetch water and the father to the market. The mongoose was left to watch the baby.", "the mother leaves with a water pot at the doorway while the mongoose stays beside the cradle"),
             ("A snake crept toward the baby, and the mongoose killed it. When the mother came back she saw blood on his mouth, and struck out in fear.", "a worried mother at the door seeing the mongoose with red on its mouth, the cradle behind"),
             ("Then she saw the dead snake, and the baby, safe and asleep. She wept for the loyal mongoose. Too late, she understood.", "the mother kneels sadly in the room, the baby asleep and a dead snake on the floor")]),
dict(series=P, title="The Jackal and the Drum", moral="A loud sound does not mean there is much inside.", plate=None,
     chars="A thin hungry jackal and an old drum lying under a tree.",
     panels=[("A hungry jackal wandered near an old battlefield and heard a great booming sound. 'Something huge is here,' he thought.", "a jackal at dusk listens nervously in a dry forest clearing"),
             ("He crept closer, trembling. The sound came again and again, louder than thunder.", "the jackal creeps toward a big drum hidden behind a tree with branches swaying"),
             ("It was a drum. Branches blew against its skin each time the wind rose. The jackal tore it open, hoping to find meat.", "the jackal tears open the drum skin with his paws"),
             ("The drum was hollow. 'So much noise, and nothing inside,' he sighed. And he learned to look before he ran.", "the jackal looks disappointed at the empty hollow drum")]),
dict(series=P, title="The Lion's Courtiers and the Camel", moral="Beware of those who flatter you into harming others.", plate="camel",
     chars="A lion, a camel, a black crow, a jackal and a wolf.",
     panels=[("A camel lost his caravan and wandered into the forest. The lion took him in as a friend.", "the lion welcomes a tall camel in a forest clearing"),
             ("One hard season, the lion could not hunt. His courtiers, a crow, a jackal and a wolf, were hungry too.", "the thin lion resting while the crow, jackal and wolf look hungry beside him"),
             ("They plotted. Each offered himself as a meal, and the lion refused each in turn. Then the camel, trusting, offered too.", "the courtiers whisper to each other, the camel bows before the lion"),
             ("'Yes!' cried the courtiers, and the trap closed. The camel learned too late: never trust those who agree only to please.", "the camel stands alone looking worried as the courtiers gather around the lion")]),
dict(series=P, title="The Sparrow and the Elephant", moral="Small friends together are stronger than a great bully.", plate=None,
     chars="A tiny brown sparrow, a green frog, a woodpecker, a fly, and a huge grey elephant.",
     panels=[("A sparrow built her nest and laid her eggs in a tree. A bully of an elephant crashed by and shook down the nest.", "a big elephant breaks a tree branch and the sparrow's nest falls, the sparrow crying above"),
             ("The heartbroken sparrow told her friends the woodpecker and the fly. 'Let us teach him a lesson,' they said.", "the sparrow, woodpecker and a fly whisper together on a branch"),
             ("The fly buzzed in the elephant's ear until he closed his eyes in delight. The woodpecker then pecked out his sight.", "the elephant with closed eyes, a fly by his ear and a woodpecker perched on his head"),
             ("Blind and thirsty, the elephant followed the frog's croak to the edge of a deep pit. Small friends had beaten a giant.", "the elephant near the edge of a pit while a frog croaks on a rock, the sparrow watching")]),
dict(series=P, title="The Hare and the Moon in the Lake", moral="A brave tongue can turn a large danger away.", plate=None,
     chars="A small white hare and a herd of grey elephants.",
     panels=[("Elephants, tired of drought, trampled through a hare colony on their way to a lake. Many hares were hurt.", "a herd of elephants walks through a hare warren at night as hares scatter"),
             ("A clever hare climbed a rock and said, 'I am the Moon's messenger. The Moon is angry that you trample us.'", "a brave hare stands on a rock speaking to the chief elephant under a full moon"),
             ("She showed the elephant king the Moon's reflection in the lake. 'See how he trembles with rage,' she said.", "the elephant king sees a shimmering moon reflection in a still lake, the hare beside him"),
             ("The frightened king bowed to the Moon and led his herd away. The hares lived in peace.", "the elephants walk away into the distance, the hares smiling in the moonlight")]),
dict(series=P, title="The Monkey and the Wedge", moral="Do not meddle in what is not your business.", plate=None,
     chars="A curious brown monkey and carpenters cutting a big log.",
     panels=[("Carpenters were splitting a big log with a wooden wedge. At midday they went to eat, leaving the log half split.", "carpenters walk away from a half-split log with a wooden wedge in the crack"),
             ("A monkey came, hopping along the log. He was curious about the wedge and sat right on the split.", "a monkey sits on the log near the wedge, his tail dangling in the split"),
             ("He gave the wedge a great tug. Out it came, and the log snapped shut on his tail. 'Ow!'", "the monkey with wide eyes as the log snaps shut on his tail"),
             ("The carpenters returned to find a very sorry monkey. He had learned to keep his paws to himself.", "the carpenters return and the monkey hangs his head")]),
dict(series=P, title="The Donkey in the Tiger's Skin", moral="A disguise is only as good as the voice behind it.", plate=None,
     chars="A grey donkey wearing a tiger skin, and a poor washerman in a dhoti.",
     panels=[("A poor washerman had a donkey that ate the farmers' crops each night. He could not afford food for it.", "a washerman in a dhoti and a thin donkey standing beside a river with piles of clothes"),
             ("One day he found a tiger's skin. He draped it over the donkey and sent him to the barley fields at night.", "the washerman drapes a tiger skin over the donkey in a field at dusk"),
             ("The farmers saw a 'tiger' and ran away, and the donkey ate in peace for many nights.", "farmers flee in fear from the donkey in the tiger skin in a barley field"),
             ("Until one night a farmer wrapped in a grey blanket sneaked near. The donkey saw a friend, and brayed. The fooled farmers knew him, and drove him off.", "the donkey with the tiger skin, mouth open braying, as farmers look on")]),
dict(series=P, title="The Two-Headed Bird", moral="When we quarrel, we all lose.", plate=None,
     chars="A colourful bird with one body and two heads, one head calm and gentle, the other angry.",
     panels=[("A strange bird lived by a river, with one body and two heads. Together they searched for food.", "a two-headed bird with one body walks along a riverbank, both heads looking around"),
             ("One head found a sweet fruit in the river and ate it. The other head, hungry too, grew jealous.", "one head of the bird eating a glowing red fruit while the other head looks angry"),
             ("The jealous head found a poisonous fruit. 'I will eat this,' he said angrily.", "the angry head pecks at a dark, poisonous-looking fruit while the calm head pleads"),
             ("The poison filled the whole body, and both heads fell sick. The bird learned that they shared one fate.", "the bird lies weak on the bank with both heads drooping, a small animal watches")]),
dict(series=P, title="The Three Fish", moral="Make a plan when danger is near, but do not despair.", plate=None,
     chars="Three fish: a quick alert fish, a clever fish, and a lazy fish that trusts fate.",
     panels=[("Three fish lived in a pond. Fishermen came one day and said they would net them all tomorrow.", "three fish in a pond, fishermen with nets visible at the bank"),
             ("The quick fish swam out that very night by the stream. The clever fish waited, thinking. The lazy fish said, 'What must be, must be.'", "one fish leaving through a narrow stream at night, two watching"),
             ("When the net came down, the clever fish floated belly-up and played dead. The fishermen tossed him aside, and he slipped away.", "a fish floating belly-up near the bank as fishermen lift a net"),
             ("The lazy fish was caught. Only planning and quickness had saved the other two.", "a fisherman lifts a net with one fish while two fish swim away in the stream")]),
dict(series=P, title="The Cats and the Monkey", moral="Do not let a third party settle your quarrels.", plate=None,
     chars="Two cats and a clever monkey with a pair of scales and a loaf of bread.",
     panels=[("Two cats found a loaf of bread and began to quarrel over who should have the bigger piece.", "two cats hissing at each other over a round loaf of bread in a village"),
             ("A monkey passed by. 'Let me divide it fairly,' he said, and brought out a scale.", "a monkey with a hand-held balance scale in front of two cats and a loaf"),
             ("He broke the bread in two, and took a bite from the heavier side to make it even. Then a bite from the other.", "the monkey nibbles bread from the scale pans while the cats watch anxiously"),
             ("Bite after bite, the bread was gone. The cats were left with crumbs, and the monkey with a full belly.", "the monkey smiling with a round tummy, two cats staring at crumbs on the scale")]),
dict(series=P, title="The Frogs and the Snake", moral="Do not befriend an enemy who has a reason to lie.", plate=None,
     chars="A large cobra and a group of green frogs led by a king frog.",
     panels=[("A frog king was angry at his own family and asked an old snake for help. The snake promised to protect him.", "a green frog king speaks to a cobra beside a well"),
             ("The snake moved into the frogs' well and ate one frog each day, telling them it was his fee.", "the cobra coiled near the water while frightened frogs hide behind stones"),
             ("The frog king cried, but the snake said, 'A friend must be paid.' The frogs shrank from fear.", "the frog king looks sadly at the empty well as the snake smiles"),
             ("At last only the frog king was left. He had trusted the wrong friend.", "an empty well and a lone frog looking at the shadow of the snake")]),
dict(series=P, title="The Donkey Without Heart or Ears", moral="A sly mind can trick a simple one.", plate=None,
     chars="A sick lion, a sly jackal and a grey donkey.",
     panels=[("A sick lion begged his jackal minister to bring him a meal. The jackal found a donkey at the riverbank.", "a thin lion in a cave and a sly jackal talking to a donkey at a river"),
             ("'Come with me,' said the jackal, 'the lion wants to make you his minister.' The donkey walked to the cave.", "the donkey walks with the jackal to the lion's cave"),
             ("The lion pounced but missed, and the donkey fled. The jackal said, 'Silly one, he only wanted to greet you!'", "the donkey running away as the lion stumbles in the cave doorway"),
             ("The donkey believed again and came back. This time the lion did not miss. The jackal had fooled a fool twice.", "the lion and jackal at the cave, the donkey nowhere in sight")]),
dict(series=P, title="The Brahmin's Pot of Flour", moral="Do not build castles in the air.", plate=None,
     chars="A poor Brahmin in a simple dhoti with a pot of flour hung above his cot.",
     panels=[("A poor Brahmin was given a pot of flour. He hung it above his bed and lay down beneath it.", "a poor man in a small hut lies on a cot looking at a hanging pot of flour"),
             ("'If famine comes, I will sell it and buy goats,' he dreamed. 'The goats will multiply, I will buy cows, then horses.'", "dream cloud above the man showing goats, cows and horses"),
             ("'I will be rich, marry, and have a son. If my wife ignores him, I will kick her—like this!'", "the man dreaming, his leg lifted in the air, hut behind him"),
             ("His foot kicked the pot, and it fell, spilling flour all over the room. His dreams were as empty as the pot.", "the man stares at a broken pot and flour spilled all over the floor")]),

# ------------------------------------------------------------------ Jataka
dict(series=J, title="The Monkey King's Bridge", moral="A true leader thinks of others before himself.", plate=None,
     chars="A large wise monkey king with a golden-brown coat, many smaller monkeys, and a king in royal clothes.",
     panels=[("A monkey king led eighty thousand monkeys in a great mango tree beside the river. Everyone ate happily.", "many monkeys feast in a huge mango tree beside a wide river"),
             ("A king of men heard about the tree and sent his archers. Monkeys leapt in terror. The only way out was across the river.", "archers on the bank aim their bows at the tree as monkeys panic"),
             ("The monkey king stretched his body from the tree to the far bank and made a living bridge. The monkeys crossed over his back.", "the monkey king stretches across the river as a living bridge while monkeys hurry across"),
             ("The king of men watched, moved. He put down his bow and cared for the monkey king. He said, 'You are the true king of this forest.'", "the human king kneels beside the tired monkey king and tends him gently")]),
dict(series=J, title="The Banyan Deer", moral="Kindness can open even a hard heart.", plate=None,
     chars="A golden deer with soft eyes and a king in royal clothes with a bow.",
     panels=[("Two herds of deer lived in a forest, each with a king. The Banyan Deer was golden, like the sun on the leaves.", "a golden stag under a giant banyan tree with his herd"),
             ("The king of the land loved hunting deer, and the deer were dying in great numbers. The two deer kings made a plan.", "the human king with a bow rides through the forest as deer flee"),
             ("One deer would go to the king each day. One day the lot fell on a mother deer with a fawn. The Banyan Deer said, 'I will go in her place.'", "the golden stag walks alone toward the palace while a mother deer and fawn watch"),
             ("The king was astonished that a deer would die for another. He lowered his bow, and spared every deer in the land.", "the king lowers his bow and touches the golden stag's head in a palace garden")]),
dict(series=J, title="The Hare in the Moon", moral="The greatest gift is the one you give freely.", plate=None,
     chars="A small white hare, a monkey, a jackal, an otter and a hungry old beggar.",
     panels=[("A hare, a monkey and a jackal lived in a forest and kept a fast on the full moon night. They promised to give food to any visitor.", "a hare, monkey and jackal sit together in a forest under a full moon"),
             ("A hungry beggar came. The monkey brought fruit, the jackal brought fish. The hare had only grass, which no traveller could eat.", "an old beggar sits with fruit and fish offered by the monkey and jackal, the hare looks sad"),
             ("'I have nothing to give but myself,' said the hare. 'Light a fire.' The beggar lit a fire and the hare, without a moment's fear, leapt in.", "a bright fire with the hare stepping toward it, the old man watching"),
             ("The flames did not burn him. The beggar was the king of the gods in disguise. To honour the hare, he drew the hare's shape on the moon, for all time.", "a huge full moon with the shape of a hare on it, forest below")]),
dict(series=J, title="The Golden Swan", moral="Greed loses everything.", plate=None,
     chars="A shining golden swan, a poor woman and her two daughters in Indian saris.",
     panels=[("A poor woman's husband died and was reborn as a golden swan. He remembered his family, and flew to their home.", "a golden swan lands on the roof of a small Indian house with a woman looking up"),
             ("'I will give you one golden feather now and then,' he said. The family sold the feathers and lived in comfort.", "the golden swan gives a shining golden feather to the woman and two girls"),
             ("But the mother grew greedy. 'Next time he comes, I will take all the feathers at once,' she said. And she did.", "the mother grabs the golden swan by the wings while the girls plead"),
             ("The feathers turned plain white in her hands. The swan grew back only white feathers and flew away, never to return.", "the woman holds plain white feathers and looks up as a swan flies far away")]),
dict(series=J, title="The Talkative Tortoise", moral="Think before you speak.", plate="tortoise",
     chars="A round green tortoise and two white geese carrying a stick.",
     panels=[("A tortoise lived in a pond with two geese friends. He talked and talked, and rarely listened.", "a tortoise talking at the edge of a pond beside two white geese"),
             ("When the pond began to dry, the geese made a plan. They held a stick in their beaks, the tortoise bit the middle. 'Do not open your mouth.'", "two geese fly holding a stick with the tortoise biting the middle"),
             ("Over a village, children pointed and laughed at the strange sight. The tortoise grew angry, and wanted to answer them.", "the tortoise hanging from the stick in the sky above a village, children pointing"),
             ("He opened his mouth to speak, and fell from the sky. A wise tortoise would have kept quiet.", "the tortoise falling from the sky toward the village square")]),
dict(series=J, title="The Crane and the Crab", moral="Cheats are caught by their own cunning.", plate=None,
     chars="A tall white crane, a red crab and small silver fish.",
     panels=[("An old crane could no longer catch fish, and thought of a trick. He stood at the pond looking sad.", "a tall white crane stands sadly at a pond with fish below and a crab at the edge"),
             ("'A great drought is coming,' he said to the fish. 'I know a deep lake. I will carry you there, one by one.'", "the crane speaks to fish in the pond, a red crab listening"),
             ("But he carried each fish to a rock and ate it. The bones piled up. The last one to ask was a crab.", "the crane on a rock with a pile of fish bones, the crab looking on"),
             ("The crab saw the fish bones and understood. He gripped the crane's neck with his claws until the cheat could do no more harm.", "the red crab grips the crane's neck with his claws on the rock")]),
dict(series=J, title="The Quails Escape the Net", moral="United, we can lift what alone we cannot.", plate=None,
     chars="A flock of small brown quails and a bird-catcher with a big net.",
     panels=[("A flock of quails lived in a meadow. A bird-catcher came each day, called like a quail, and threw a net over them.", "a bird-catcher in a meadow spreading a net toward a flock of quails"),
             ("The wise leader quail said, 'When the net comes down, we all lift together and fly away with it.'", "the leader quail speaking to the flock in the grass"),
             ("The next day the net fell. The quails all lifted at once, and flew with the net over the thorn bushes.", "quails flying together carrying the net over thorn bushes"),
             ("The bird-catcher chased in vain. The quails were free, so long as they stayed together.", "the bird-catcher stares up angrily at the flying quails and net")]),
dict(series=J, title="The Parrot and the Forest Fire", moral="Even a small act of love can move the heavens.", plate=None,
     chars="A small green parrot, a river, and a king of the gods in golden light.",
     panels=[("A great fire broke out in the forest. The animals fled, but a little parrot could not leave the burning trees.", "a forest burning at dusk with animals running and a small parrot on a branch"),
             ("He flew to the river, dipped his wings in the water, and flew back to sprinkle the flames, again and again.", "the small parrot with wet wings flies over the river toward the fire"),
             ("The king of the gods saw him from heaven. 'Little bird, do you think your drops can stop a fire?'", "a glowing king of the gods with a crown appears in the sky above the small parrot"),
             ("'I do what I can,' said the parrot. Moved, the god sent down a shower of rain, and the fire was gone.", "rain pours over the forest and the fire goes out as the parrot looks up")]),
dict(series=J, title="The Kind Buffalo", moral="Patience is the sign of a strong heart.", plate=None,
     chars="A large calm black buffalo and a naughty little monkey.",
     panels=[("A big black buffalo lived in the forest. A naughty monkey liked to jump on his back, pull his tail and tease him.", "a monkey sits on the back of a calm buffalo in a forest"),
             ("Every day the monkey played tricks. The buffalo only shook his head and walked on.", "the monkey pulls the buffalo's tail while the buffalo walks patiently"),
             ("One day a spirit of the forest said, 'Why do you not stop him?' The buffalo said, 'It is easy to anger; it is hard to forgive.'", "a glowing forest spirit speaks to the buffalo as the monkey watches from a tree"),
             ("Ashamed, the monkey stopped his teasing and became the buffalo's friend.", "the monkey and buffalo rest together under a tree")]),
dict(series=J, title="The Bull Who Won the Bet", moral="Kind words win where harsh words fail.", plate=None,
     chars="A large strong white bull named Nandi and a farmer in a dhoti.",
     panels=[("A farmer had a strong bull named Nandi. One day the bull said, 'Bet a thousand coins that I can pull a hundred carts.'", "a strong white bull speaking to a farmer in a village lane"),
             ("The farmer bet his neighbour, but then shouted at the bull, 'Pull, you rascal! Pull, you brute!' The bull stood still.", "a farmer shouting at the bull hitched to a line of heavy carts"),
             ("The farmer lost his money. Nandi said, 'You spoke to me roughly. Bet again, and call me kindly.'", "the bull turns his head to the sad farmer"),
             ("This time the farmer said, 'Pull, my beauty! Pull, my hero!' The bull pulled all hundred carts and the farmer won.", "the white bull pulling a long line of carts as villagers cheer")]),
dict(series=J, title="The Two Merchants and the Golden Bowl", moral="Honesty is worth more than gold.", plate=None,
     chars="Two travelling merchants (one greedy, one honest) in Indian clothes and a poor old woman with a dusty bowl.",
     panels=[("Two pedlars visited a village. A poor old woman had a dusty old bowl. She did not know it was solid gold.", "a poor old woman holds a dusty old bowl at the door of her small house, a pedlar behind her"),
             ("The greedy pedlar tried to cheat her. 'This bowl is worthless. Take a small trinket for it,' he said, and she refused.", "a greedy pedlar in a turban talks to the old woman at a doorway"),
             ("The honest pedlar next came. He told the woman it was gold and paid her fairly for it.", "the honest pedlar hands coins to the old woman"),
             ("The greedy pedlar returned, found the bowl gone, and wept. He had lost a treasure by being unkind.", "the greedy pedlar sits sadly on the ground holding his head, the old woman smiling at the door")]),
dict(series=J, title="The Blind Men and the Elephant", moral="Each of us sees only part of the truth.", plate=None,
     chars="A large grey elephant, and several blind men in simple clothes each touching a part.",
     panels=[("A king asked some blind men to describe an elephant. He brought them to touch the beast.", "a king in a palace courtyard with an elephant and several blind men standing near")
             ,("One touched the trunk and said, 'An elephant is like a snake.' Another touched the leg and said, 'It is a pillar.'", "blind men touching the elephant's trunk and leg")
             ,("One touched the ear: 'a fan.' Another touched the tail: 'a rope.' Another the side: 'a wall.'", "blind men touching the ear, tail and side of the elephant")
             ,("They began to shout and quarrel. The king smiled. 'Each of you has a part,' he said, 'but none of you has the whole.'", "the blind men arguing while the king smiles gently")]),
dict(series=J, title="The Dead Mouse Fortune", moral="A wise mind can make something of nothing.", plate=None,
     chars="A poor but clever young man in a simple dhoti, a merchant and a cat.",
     panels=[("A poor but clever young man saw a dead mouse on the road. A wise merchant nearby said, 'A clever man can build a fortune from that.'", "a young man points to a dead mouse on a road, a merchant walks by"),
             ("The young man sold the mouse for a copper coin to a man with a cat. With the coin he bought sweets and water for thirsty flower-gatherers.", "the young man sells the mouse to a man with a cat and buys sweets"),
             ("The flower-gatherers gave him flowers. He sold the flowers at market and grew his trade, day by day.", "the young man sells flowers from a basket in a busy Indian market"),
             ("Soon he had a fortune. He went to thank the merchant, who was so impressed that he gave the young man his daughter in marriage.", "the young man bows before the merchant in a merchant's house, a young woman beside them")]),
dict(series=J, title="The Two Parrots", moral="We become like those we keep company with.", plate=None,
     chars="Two green parrots, a hermit in orange robes and a rough robber.",
     panels=[("Two parrot chicks fell from the same nest in a storm. One was found by a rough robber, the other by a gentle hermit.", "two parrot chicks in a storm on the ground and two men walking toward them"),
             ("The parrot raised by the robber learned to shout rude words. The parrot raised by the hermit learned kind ones.", "one parrot squawking beside a rough man and another parrot beside a calm hermit"),
             ("One day a king passed by. The rude parrot shouted at him and the king rode away angry.", "a green parrot at a robber's hut shouting at a passing king on a horse"),
             ("The hermit's parrot greeted the king warmly, and was invited to stay. Company can shape a heart.", "the hermit's parrot bowing politely to the king outside a hermitage")]),
dict(series=J, title="The Hare Who Heard a Thud", moral="Check the facts before you run.", plate=None,
     chars="A small startled hare, a wise lion, and a herd of forest animals.",
     panels=[("A hare was sleeping under a palm tree when something went thud behind him. He jumped up and shouted, 'The earth is breaking!'", "a hare wakes suddenly under a palm tree with a thud sound behind him"),
             ("Another hare heard, then a deer, then a herd of elephants. All fled in panic without asking why.", "a stream of animals running through the forest, hares, deer and elephants"),
             ("A wise lion stopped them. 'Who saw the earth breaking?' He asked the hare. 'I heard a thud,' said the hare.", "a wise lion stops the animals and questions the small hare"),
             ("They went back together. A ripe palm fruit had fallen from the tree. The animals laughed with relief.", "the lion and the hare beside a fallen palm fruit while animals laugh")]),
dict(series=J, title="The Baby Quail's Truth", moral="Truth and love hold great power.", plate=None,
     chars="A tiny baby quail that cannot fly, a burning forest, and a king of the gods.",
     panels=[("A baby quail, too young to fly, sat in its nest. His parents had to leave to find food.", "a tiny baby quail alone in a nest on the ground in a green meadow"),
             ("Suddenly a wild fire swept toward the meadow. The parents flew off in fear and left the baby behind.", "flames roll through dry grass toward the baby quail in its nest"),
             ("The baby said, 'By the power of truth, I have not yet grown wings, and my parents have gone. Let the fire spare me.'", "the tiny quail looking up bravely as a soft light forms around it"),
             ("The fire split around the nest as if a wall stood there. The truth of a small heart had turned back the flames.", "flames part around the nest in a circle of green, the baby quail unharmed")]),
]
